export const SCHOOL_DAY_DATA = [
    {
        id: 1,
        title: 'Учебная часть',
        description: "Глубоко осваиваем программу с&nbsp;поддержкой педагогов‑наставников, закрепляем знания в&nbsp;проектах и&nbsp;выполняем домашние задания в&nbsp;школе",
        background: "violet-light",
        icon: "icon_monitor",
        iconWidth: "115",
        iconHeight: "110",
        imageDesktop: "/images/desktop/27-image.webp",
        imageMobile: "/images/mobile/27-image.png",
        imageAlt: "Учебная часть",
        imageWidth: "262",
        imageHeight: "303",
        additionalContent: '9:00–14:00',
        type: 'animation'
    },
    {
        id: 2,
        title: 'Обед и отдых',
        description: "После уроков дети получают тёплый сбалансированный обед: первое, второе, овощи/салат и&nbsp;напиток",
        background: "green",
        imageDesktop: "/images/desktop/28-image.webp",
        imageMobile: "/images/mobile/28-image.webp",
        imageAlt: "Обед и отдых изображение",
        imageWidth: "327",
        imageHeight: "203",
        additionalContent: '14:00–15:00',
        type: 'info'
    },
    {
        id: 3,
        title: 'Интеллектуальные занятия',
        description: "Скорочтение, ментальная арифметика, логика, шахматы, литературный клуб и&nbsp;интеллектуальные игры помогают развивать внимание, а&nbsp;также&nbsp;критическое и&nbsp;креативное&nbsp;<span class='text-wrap'>мышление</span>",
        background: "green",
        imageDesktop: "/images/desktop/29-image.webp",
        imageMobile: "/images/mobile/29-image.webp",
        imageAlt: "Интеллектуальные занятия",
        imageWidth: "174",
        imageHeight: "174",
        additionalContent: '15:00–16:30',
        type: 'animation'
    },
    {
        id: 4,
        title: 'Творчество и спорт',
        description: "Студии по&nbsp;выбору: робототехника, программирование, изобразительное искусство, хореография, вокал. Спорт:&nbsp;футбол и&nbsp;общая физическая подготовка",
        background: "blue",
        imageDesktop: "/images/desktop/30-image.webp",
        imageMobile: "/images/mobile/30-image.webp",
        imageAlt: "Творчество и спорт",
        imageWidth: "320",
        imageHeight: "320",
        additionalContent: '16:30–17:30',
        type: 'animation'
    },
    {
        id: 5,
        title: 'Завершение дня',
        description: 'Спокойно заканчиваем день: подводим итоги, играем, читаем, ждём родителей. Ребёнок уходит домой уже с&nbsp;готовыми уроками и&nbsp;без ощущения спешки',
        background: "blue-light",
        imageDesktop: "/images/desktop/31-image.webp",
        imageMobile: "/images/mobile/31-image.png",
        imageAlt: "Завершение дня",
        imageWidth: "238",
        imageHeight: "238",
        additionalContent: '17:30–18:00',
        type: 'animation'
    },
]