export const ACTIVE_DAY_CAMP_DATA = [
    {
        id: 1,
        title: "Практические занятия",
        icon: "icon_monitor-light",
        iconWidth: "82",
        iconHeight: "77",
        description: "Эксперименты, исследовательские задачи, работа руками и&nbsp;головой",
        background: "violet",
        imageDesktop: "/images/desktop/39-image.webp",
        imageMobile: "/images/desktop/39-image.webp",
        imageAlt: "Практические занятия",
        imageWidth: "174",
        imageHeight: "174",
    },
    {
        id: 2,
        title: 'Проектная деятельность',
        description: "Ребёнок создаёт свой мини-проект, учится мыслить, искать решения, работать в&nbsp;команде",
        background: "orange",
        imageDesktop: "/images/desktop/41-image.webp",
        imageMobile: "/images/mobile/41-image.webp",
        imageAlt: "Проектная деятельность",
        imageWidth: "174",
        imageHeight: "174",
    },
    {
        id: 3,
        title: 'Мастер-классы',
        description: "Творчество, технологии, игры, новые форматы, которые можно попробовать без&nbsp;страха ошибиться",
        icon: "icon_palette",
        iconWidth: "85",
        iconHeight: "90",
        background: "blue-light",
        imageDesktop: "/images/desktop/40-image.webp",
        imageMobile: "/images/mobile/40-image.webp",
        imageAlt: "Мастер-классы",
        imageWidth: "408",
        imageHeight: "319",
    },
    {
        id: 4,
        title: 'Активности на&nbsp;свежем воздухе',
        description: "Игры, движения, прогулки&nbsp;&mdash; чтобы&nbsp;день был&nbsp;живым и&nbsp;насыщенным",
        background: "green",
        imageDesktop: "/images/desktop/42-image.webp",
        imageMobile: "/images/mobile/42-image.webp",
        imageAlt: "Активности",
        imageWidth: "330",
        imageHeight: "230",
    },
    {
        id: 5,
        title: 'Новые навыки',
        description: 'Самостоятельность, креативность, умение договариваться&nbsp;и&nbsp;презентовать свои идеи',
        background: "red",
        imageDesktop: "/images/desktop/43-image.webp",
        imageMobile: "/images/mobile/43-image.webp",
        imageAlt: "Новые навыки",
        imageWidth: "238",
        imageHeight: "238",
    },
]